#!/bin/bash
# makeit <javafile.java>
export TOMCAT_HOME=/etc/jakarta-tomcat-3.2.3
export JAVA_HOME=/usr/java/jdk1.3.1
export PATH=$JAVA_HOME/bin:$PATH
export REPBOT_HOME=$TOMCAT_HOME/webapps/repbot
export REPBOT_CLASSES=$REPBOT_HOME/WEB-INF/classes
export MMMYSQL_HOME=$TOMCAT_HOME/mmmysql
export MMMYSQL_CLASSES=$MMMYSQL_HOME/mm.mysql-2.0.4/mysql.jar
java \
	-classpath \
	$MMMYSQL_CLASSES:$REPBOT_CLASSES \
	userDB.UserDBImplementation
